repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: ["--check", "-l102"]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: ["--max-line-length=102"]
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    - id: mypy
      args: ["--ignore-missing-imports", "--install-types", "--non-interactive", "--check"]
